.dataset_defaults: &ds_defaults
  dataset: "stanfordcars"
  n_shot: 16

.model_defaults: &m_defaults
  backbone: 'ViT-B/16'
  upper_triangle: True

.training_defaults: &t_defaults
  epochs: 100
  loss: "contrastive"
  optimizer: "adamw"
  lr: 1e-4
  weight_decay: 0.1
  save_best: False

16_shot_vit16:
  Dataset:
    <<: *ds_defaults
  Model:
    <<: *m_defaults
  Training:
    <<: *t_defaults
    lr: 1e-3
    weight_decay: 1e-4
    epochs: 50

8_shot_vit16:
  Dataset:
    <<: *ds_defaults
    n_shot: 8
  Model:
    <<: *m_defaults
  Training:
    <<: *t_defaults
    lr: 1e-3
    weight_decay: 1e-4
    epochs: 50

4_shot_vit16:
  Dataset:
    <<: *ds_defaults
    n_shot: 4
  Model:
    <<: *m_defaults
  Training:
    <<: *t_defaults
    lr: 1e-3
    weight_decay: 1e-4
    epochs: 50

2_shot_vit16:
  Dataset:
    <<: *ds_defaults
    n_shot: 2
  Model:
    <<: *m_defaults
  Training:
    <<: *t_defaults
    lr: 1e-3
    weight_decay: 1e-4
    epochs: 50

1_shot_vit16:
  Dataset:
    <<: *ds_defaults
    n_shot: 1
  Model:
    <<: *m_defaults
  Training:
    <<: *t_defaults
    lr: 1e-3
    weight_decay: 1e-4
    epochs: 50

16_shot_rn50:
  Dataset:
    <<: *ds_defaults
  Model:
    <<: *m_defaults
    backbone: 'RN50'
  Training:
    <<: *t_defaults


